export const ACCOUNT_SIGNUP_EMAIL_REQUEST = 'ACCOUNT_SIGNUP_EMAIL_REQUEST'
export const ACCOUNT_SIGNUP_EMAIL_SUCCESS = 'ACCOUNT_SIGNUP_EMAIL_SUCCESS'
export const ACCOUNT_SIGNUP_EMAIL_FAIL = 'ACCOUNT_SIGNUP_EMAIL_FAIL'

export const ACCOUNT_SIGNUP_VERIFY_REQUEST = 'ACCOUNT_SIGNUP_VERIFY_REQUEST'
export const ACCOUNT_SIGNUP_VERIFY_SUCCESS = 'ACCOUNT_SIGNUP_VERIFY_SUCCESS'
export const ACCOUNT_SIGNUP_VERIFY_FAIL = 'ACCOUNT_SIGNUP_VERIFY_FAIL'

export const ACCOUNT_SIGNUP_BASIC_REQUEST = 'ACCOUNT_SIGNUP_BASIC_REQUEST'
export const ACCOUNT_SIGNUP_BASIC_SUCCESS = 'ACCOUNT_SIGNUP_BASIC_SUCCESS'
export const ACCOUNT_SIGNUP_BASIC_FAIL = 'ACCOUNT_SIGNUP_BASIC_FAIL'