export const ACCOUNT_SIGNUP_EMAIL_REQUEST = 'ACCOUNT_SIGNUP_EMAIL_REQUEST'
export const ACCOUNT_SIGNUP_EMAIL_SUCCESS = 'ACCOUNT_SIGNUP_EMAIL_SUCCESS'
export const ACCOUNT_SIGNUP_EMAIL_FAIL = 'ACCOUNT_SIGNUP_EMAIL_FAIL'

export const ACCOUNT_SIGNUP_VERIFY_REQUEST = 'ACCOUNT_SIGNUP_VERIFY_REQUEST'
export const ACCOUNT_SIGNUP_VERIFY_SUCCESS = 'ACCOUNT_SIGNUP_VERIFY_SUCCESS'
export const ACCOUNT_SIGNUP_VERIFY_FAIL = 'ACCOUNT_SIGNUP_VERIFY_FAIL'

export const ACCOUNT_SIGNUP_BASIC_REQUEST = 'ACCOUNT_SIGNUP_BASIC_REQUEST'
export const ACCOUNT_SIGNUP_BASIC_SUCCESS = 'ACCOUNT_SIGNUP_BASIC_SUCCESS'
export const ACCOUNT_SIGNUP_BASIC_FAIL = 'ACCOUNT_SIGNUP_BASIC_FAIL'

export const ACCOUNT_LOGIN_EMAIL_REQUEST = 'ACCOUNT_LOGIN_EMAIL_REQUEST'
export const ACCOUNT_LOGIN_EMAIL_SUCCESS = 'ACCOUNT_LOGIN_EMAIL_SUCCESS'
export const ACCOUNT_LOGIN_EMAIL_FAIL = 'ACCOUNT_LOGIN_EMAIL_FAIL'

export const ACCOUNT_LOGIN_VERIFY_REQUEST = 'ACCOUNT_LOGIN_VERIFY_REQUEST'
export const ACCOUNT_LOGIN_VERIFY_SUCCESS = 'ACCOUNT_LOGIN_VERIFY_SUCCESS'
export const ACCOUNT_LOGIN_VERIFY_FAIL = 'ACCOUNT_LOGIN_VERIFY_FAIL'

export const ACCOUNT_LOGIN_PASSWORD_REQUEST = 'ACCOUNT_LOGIN_PASSWORD_REQUEST'
export const ACCOUNT_LOGIN_PASSWORD_SUCCESS = 'ACCOUNT_LOGIN_PASSWORD_SUCCESS'
export const ACCOUNT_LOGIN_PASSWORD_FAIL = 'ACCOUNT_LOGIN_PASSWORD_FAIL'

export const ACCOUNT_SLUG_CHECK_REQUEST = 'ACCOUNT_SLUG_CHECK_REQUEST'
export const ACCOUNT_SLUG_CHECK_SUCCESS = 'ACCOUNT_SLUG_CHECK_SUCCESS'
export const ACCOUNT_SLUG_CHECK_FAIL = 'ACCOUNT_SLUG_CHECK_FAIL'

export const ACCOUNT_SLUG_CHANGE_REQUEST = 'ACCOUNT_SLUG_CHANGE_REQUEST'
export const ACCOUNT_SLUG_CHANGE_SUCCESS = 'ACCOUNT_SLUG_CHANGE_SUCCESS'
export const ACCOUNT_SLUG_CHANGE_FAIL = 'ACCOUNT_SLUG_CHANGE_FAIL'

export const ACCOUNT_CHANGE_REQUEST = 'ACCOUNT_CHANGE_REQUEST'
export const ACCOUNT_CHANGE_SUCCESS = 'ACCOUNT_CHANGE_SUCCESS'
export const ACCOUNT_CHANGE_FAIL = 'ACCOUNT_CHANGE_FAIL'